# Generated by Django 5.1.3 on 2025-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
